# Sources
source ~/.config/kak/ctrlf.kak 
source ~/.config/kak/fzf.kak

# Sets
colorscheme github
set global tabstop 2
set global indentwidth 2

# Maps
map global insert <backtab> '<a-;><lt>'
map global normal <backtab> '<a-;><lt>'
map global normal <tab> '<a-;><gt>'
map global normal <c-n> ':%sh{tmux-shuffle l}<ret>'
map global normal <c-k> ':%sh{tmux-shuffle r}<ret>'
map global user p '<a-!>pbpaste<ret>'
map global user P '!pbpaste<ret>'
map global user f ':ctrlf<ret>'
map global user t ':fzf-file<ret>'
map global user / ':ranger<ret>'
map global user <space> ':%sh{tmux joinp -s quik:0}<ret>'

# Hooks
hook global InsertChar \t %{exec -draft -itersel h@}
hook global WinCreate .* %{addhl number_lines}
hook global NormalKey y|d|c %{ nop %sh{
  printf %s "$kak_reg_dquote" | pbcopy
}}
hook global RuntimeError "\d+:\d+: '\w+' (.*): is a directory" %{ %sh{
  directory=$(expr $kak_hook_param : "[0-9]*:[0-9]*: '[a-z]*' \\(.*\\): is a directory")
  echo ranger $directory
}}
hook global BufCreate .*[.](jsx) %{
  set buffer filetype javascript
}
hook global BufCreate .* %{
  %sh{tmux renamew $kak_bufname}
}
