alias ls='ls -AF'
alias c='clear'
alias s='git status'
alias a='git add'
alias a.="git add ."
alias gr="git reset --hard HEAD"
alias ch='git checkout'
alias b='git branch'
alias cb='git checkout -b'
alias pl='git pull origin'
alias ps='git push origin'
alias gc='git commit -m'
alias build='npm run build'
alias start='npm run start'
