#!/usr/bin/env bash

state=`osascript -e 'tell application "Spotify" to player state as string'`
if [ $state != "stopped" ];then
  info=`head -n 1 $HOME/.spotstat.state 2> /dev/null`
  dur=`tail -n 1 $HOME/.spotstat.state 2> /dev/null`
  pos=`osascript -e 'tell application "Spotify"
    set pos to (player position div 1) as text
    set tM to (pos div 60) as text
    set tS to (pos mod 60) as text
    if length of tS is less than 2 then
      set tS to ("0" & tS) as text
    end if
    set myTime to tM & ":" & tS
    end tell
    return myTime'`
  if [ $state == "playing" ]; then
    statechar="〜"
  else
    statechar="■"
  fi
  spotstatasync &
  echo "$statechar $info $pos / $dur"
fi
